name: "Maven Publish"
#name: Publish package to GitHub Packages
#on:
#  release:
#    types: [created]

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: ./mvnw clean package
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "master"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@github.com"
          #          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
          # Release
          maven-repo-server-id: ${MAVEN_SERVER_ID}
          maven-repo-server-username: dstoianov
          maven-repo-server-password: ${{ secrets.GITHUB_TOKEN }}
          maven-release-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"

          # Publish artifacts to GitHub Packages
          maven-publish-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"
          maven-release-publish: "true"
          maven-snapshot-publish: "true"

