# documentation
# https://github.com/marketplace/actions/github-tag
# https://github.com/marketplace/actions/create-a-release

name: "Maven Deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Deploy to GitHub
        run: ./mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v5.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          #default_bump: patch
#          default_bump: minor
#          create_annotated_tag: true
#
#      - name: Create GitHub Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.tag_version.outputs.new_tag }}
#          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}

#      - name: Release
#        uses: qcastel/github-actions-maven-release@master
#        env:
#          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
#        with:
#          #          release-branch-name: "master"
#          git-release-bot-name: "release-bot"
#          git-release-bot-email: "release-bot@github.com"
#          #          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#          access-token: ${{ secrets.GITHUB_TOKEN }}
#          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
