name: "Maven PR Compile"

on:
  [ pull_request ]

jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          cache: 'maven'
      - name: Compile
        run: ./mvnw clean compile
