# documentation
# https://github.com/marketplace/actions/github-tag
# https://github.com/marketplace/actions/create-a-release

name: "Maven Simple"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JAVA
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build/Verify with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
        with:
          #          release-branch-name: "master"
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@github.com"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          #          access-token: ${{ secrets.GITHUB_TOKEN }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"

#      - name: Configure Git user
#        run: |
#          git config user.email "actions@github.com"
#          git config user.name "GitHub Actions"
#      - name: Publish JAR
#        run: mvn --batch-mode -DskipTests release:prepare release:perform
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Publish package
#        run: mvn --batch-mode deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - run: mkdir staging && cp target/*.jar staging
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: staging


